"use client";
import { useEffect,useRef,useState } from 'react';
import { ArrowUpRight,ArrowDown,Pause,Play } from 'lucide-react';
export default function MotionHero(){const surface=useRef<HTMLDivElement>(null);const canvas=useRef<HTMLCanvasElement>(null);const [paused,setPaused]=useState(false);const [reduced,setReduced]=useState(false);
useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(m.matches);sync();m.addEventListener('change',sync);return()=>m.removeEventListener('change',sync)},[]);
useEffect(()=>{const el=surface.current,c=canvas.current;if(!el||!c)return;const ctx=c.getContext('2d');if(!ctx)return;let w=1,h=1,raf=0,frame=0,px=0,py=0,tx=0,ty=0,visible=true;const active=!paused&&!reduced;
const resize=()=>{w=el.clientWidth;h=el.clientHeight;const d=Math.min(devicePixelRatio,1.5);c.width=w*d;c.height=h*d;c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);draw()};
const draw=()=>{ctx.clearRect(0,0,w,h);px+=(tx-px)*.045;py+=(ty-py)*.045;const time=frame*.007;for(let j=0;j<(w<500?28:46);j++){ctx.beginPath();for(let i=0;i<=(w<500?72:110);i++){const a=i/(w<500?72:110)*Math.PI*2;const ripple=Math.sin(a*3+time+j*.055)*18;const rx=w*.30+j*1.85+ripple;const ry=h*.24+j*1.05;const x=w*.52+Math.cos(a)*rx+Math.sin(a*2+time)*27+px*25;const y=h*.49+Math.sin(a)*ry+Math.cos(a*3+time)*20+py*20;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.closePath();ctx.strokeStyle=j%6===0?'rgba(249,189,0,.76)':`rgba(249,${164+j},${30+j},${.16+j*.009})`;ctx.lineWidth=.75;ctx.stroke()}el.style.setProperty('--rx',(-py*6)+'deg');el.style.setProperty('--ry',(px*7)+'deg');};
const loop=()=>{raf=0;if(!visible||!active||document.hidden)return;frame++;draw();raf=requestAnimationFrame(loop)};const syncAnimation=()=>{cancelAnimationFrame(raf);raf=0;if(visible&&active&&!document.hidden)raf=requestAnimationFrame(loop)};const move=(e:PointerEvent)=>{if(e.pointerType==='touch'||!active)return;const b=el.getBoundingClientRect();tx=(e.clientX-b.left)/w*2-1;ty=(e.clientY-b.top)/h*2-1};const leave=()=>{tx=ty=0};const ro=new ResizeObserver(resize);ro.observe(el);const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;syncAnimation()});io.observe(el);el.addEventListener('pointermove',move);el.addEventListener('pointerleave',leave);document.addEventListener('visibilitychange',syncAnimation);resize();syncAnimation();return()=>{cancelAnimationFrame(raf);document.removeEventListener('visibilitychange',syncAnimation);ro.disconnect();io.disconnect();el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',leave)}},[paused,reduced]);
return <section className="hero wrap"><div className="hero-topline"><span><i/>BAĞIMSIZ DİJİTAL AJANS</span><span>İSTANBUL · TÜRKİYE</span></div><div className="hero-grid"><div className="hero-copy"><p className="eyebrow">FİKİRDEN ETKİYE.</p><h1>Dijitalde<br/>iz bırak.<br/><em>Etki yarat.</em></h1><p>Cesur fikirleri güçlü stratejilerle buluşturuyoruz. Markanız için tasarlıyor, geliştiriyor ve büyümenin izini sürüyoruz.</p><div className="hero-actions"><a href="/iletisim" className="pill brand">Projenizi konuşalım <ArrowUpRight size={20}/></a><a href="/referanslar" className="quiet-link">Bize güvenen markalar <ArrowUpRight size={17}/></a></div></div><div ref={surface} className="motion-surface" aria-label="Fare hareketiyle şekil değiştiren soyut Aymek animasyonu"><canvas ref={canvas} aria-hidden="true"/><div className="motion-brand" aria-hidden="true"><img src="/aymek/logo.png" alt="" width="1068" height="425"/></div><span className="orbit-tag tag-one">STRATEJİ</span><span className="orbit-tag tag-two">KREATİF</span><span className="orbit-tag tag-three">PERFORMANS</span><div className="motion-caption"><span>AYMEK / INTERACTIVE STUDIO<br/><small>{reduced?'Hareket azaltıldı':'Hareket ettir. Farkı hisset.'}</small></span><button aria-label={paused?'Animasyonu başlat':'Animasyonu duraklat'} onClick={()=>setPaused(!paused)} disabled={reduced}>{paused||reduced?<Play size={16}/>:<Pause size={16}/>}</button></div></div></div><div className="hero-bottom"><a href="#kesfet"><ArrowDown size={16}/> KEŞFETMEYE DEVAM ET</a><span>Güçlü marka. Doğru kitle. Ölçülebilir etki.</span><span>01 — 06</span></div></section>}
