export const articles={
"google-ads-butcesi":{tag:"GOOGLE ADS",title:"Google Ads bütçesi nasıl planlanır?",intro:"Sağlıklı reklam bütçesi rakiplerin harcadığı rakamdan değil, işletmenin hedeflerinden ve dönüşüm ekonomisinden hesaplanır.",parts:[["Hedefi rakama çevirin","Aylık nitelikli telefon, form veya satış hedefini ve kabul edilebilir müşteri edinme maliyetini belirleyin."],["Arama hacmini ölçün","Hedef kelimelerin hacmi, tıklama maliyeti ve bölgesel rekabet bütçenin erişebileceği talebi belirler."],["Test alanı bırakın","İlk dönem hangi kelime, reklam ve sayfanın çalıştığını öğrenme dönemidir."],["Kârlılığı izleyin","Ucuz tıklama tek başına başarı değildir; satış oranı ve kâr marjı birlikte değerlendirilmelidir."]]},
"google-haritalar-gorunurluk":{tag:"YEREL PAZARLAMA",title:"Google Haritalar görünürlüğü nasıl geliştirilir?",intro:"Yerel görünürlük tek bir ayarla değil, profil bütünlüğü ve güven sinyallerinin düzenli yönetimiyle gelişir.",parts:[["Doğru kategori","Ana kategori işletmenin temel faaliyetini açıkça tanımlamalıdır."],["Profil bütünlüğü","Adres, telefon, saatler, hizmetler ve web sitesi güncel olmalıdır."],["Görsel düzen","Güncel fotoğraflar ve gönderiler müşterinin kararını kolaylaştırır."],["Yorum yönetimi","Gerçek müşterilerden yorum istemek ve profesyonel yanıt vermek güveni güçlendirir."]]},
"sosyal-medya-stratejisi":{tag:"SOSYAL MEDYA",title:"Paylaşım takviminden marka stratejisine",intro:"Düzenli paylaşım görünürlük sağlar; güçlü iletişim hedef, mesaj ve içerik rollerinin birlikte planlanmasını gerektirir.",parts:[["İçerik hedefi","Her içerik bilgilendirme, güven, etkileşim veya satış hedeflerinden birine hizmet etmelidir."],["İçerik sütunları","Ürün, uzmanlık, müşteri soruları ve marka kültürü için tekrar edilebilir alanlar belirleyin."],["Tek marka sesi","Görseller, başlıklar ve yanıt dili aynı marka karakterini yansıtmalıdır."],["Doğru metrikler","Beğeninin yanında profil ziyareti, bağlantı tıklaması, mesaj ve satış katkısını izleyin."]]},
"e-ticaret-buyume-plani":{tag:"E-TİCARET",title:"E-ticaret sitesi nasıl sürdürülebilir büyütülür?",intro:"Büyüme yalnızca reklam bütçesini artırmak değildir; ürün, teklif, trafik, dönüşüm ve tekrar satın alma birlikte geliştirilmelidir.",parts:[["Ticari hedef","Ciro kadar brüt kâr, müşteri edinme maliyeti ve nakit döngüsü de izlenmelidir."],["Ürün önceliği","Marjı, stoku ve talebi güçlü ürün gruplarına odaklanın."],["Site deneyimi","Mobil hız, ürün bilgisi, teslimat ve ödeme güveni kararı kolaylaştırmalıdır."],["Müşteriyi geri kazanın","E-posta, yeniden pazarlama ve sadakat akışları ilk satışın değerini büyütür."]]},
"shopify-magaza-kontrol-listesi":{tag:"SHOPIFY",title:"Shopify mağazası yayına alınmadan önce kontrol listesi",intro:"Sağlıklı bir mağaza ürün verisi, mobil deneyim, ödeme, ölçüm ve operasyonun birlikte test edilmesiyle hazır olur.",parts:[["Ürün yapısı","Müşterinin aradığı ürüne en az adımla ulaşacağı koleksiyon ve filtre yapısını kurun."],["Mobil akış","Menüden ödeme adımına kadar tüm süreci gerçek telefonda test edin."],["Ölçüm","GA4, Google Ads ve Meta olaylarının doğru değer taşıdığını kontrol edin."],["Operasyon","Stok, kargo, iptal ve iade mesajlarını test siparişiyle doğrulayın."]]},
"yerel-reklam-stratejisi":{tag:"YEREL PAZARLAMA",title:"Yerel işletmeler için reklam ve harita stratejisi",intro:"Yerel büyümede reklam, harita profili, yorumlar ve telefon deneyimi aynı müşteri yolculuğunun parçalarıdır.",parts:[["Hizmet bölgesi","Yalnızca ulaşabildiğiniz ve kârlı hizmet verebildiğiniz konumlara odaklanın."],["Tutarlı mesaj","Reklam mesajı, işletme kategorisi ve açılış sayfası birbiriyle uyumlu olmalıdır."],["Arama kalitesi","Telefon tıklaması kadar nitelikli görüşme ve randevu sonucunu da takip edin."],["Yorum sistemi","Memnun müşteriden doğru zamanda geri bildirim isteyen etik bir süreç kurun."]]},
"remarketing-rehberi":{tag:"YENİDEN PAZARLAMA",title:"Yeniden pazarlama kampanyaları nasıl planlanır?",intro:"Etkileşim düzeyine göre ayrılan kitleler daha ilgili mesajlar ve kontrollü reklam sıklığı sağlar.",parts:[["Segmentleyin","Ürün inceleyen, sepete ekleyen veya formu yarıda bırakan kullanıcıları ayırın."],["Süreyi ayarlayın","Kısa ve uzun karar döngüleri için aynı üyelik süresi kullanılmamalıdır."],["Dışlamaları kurun","Gerektiğinde mevcut müşterileri yeni müşteri reklamlarından çıkarın."],["Frekansı izleyin","Aşırı gösterimi önlemek için sıklık ve kreatif yenilemeyi takip edin."]]},
"dijital-ajans-secimi":{tag:"AJANS REHBERİ",title:"Dijital ajans seçerken sorulması gereken sorular",intro:"Ajans seçiminde çalışma düzeni, hesap mülkiyeti, ölçüm yaklaşımı ve sorumluluk sınırları değerlendirilmelidir.",parts:[["Hesaplar kimin?","Reklam ve analiz hesaplarının işletmeniz adına kurulacağını netleştirin."],["Başarı nedir?","Tıklamanın ötesinde telefon, form, satış ve kârlılık göstergelerini sorun."],["Kapsam nedir?","Kreatif, içerik, yazılım, çekim ve medya bütçesinin ayrı olup olmadığını öğrenin."],["Sonraki aksiyon","İyi rapor geçmişin yanında sonraki testleri ve sorumluları da belirtir."]]}
}as const;
export type ArticleSlug=keyof typeof articles;
