export const sectors={
 "e-ticaret":{title:"E-Ticaret",headline:"Trafiği satışa, müşteriyi sadakate dönüştüren büyüme sistemi.",problem:"E-ticarette yalnızca reklam vermek yetmez. Ürün, teklif, kreatif, site deneyimi ve ölçüm birlikte çalışmalıdır.",solutions:["Google Shopping ve Performance Max","Meta katalog ve yeniden pazarlama","Dönüşüm odaklı landing page","Kreatif test ve kampanya planı"]},
 "saglik-ve-klinik":{title:"Sağlık & Klinik",headline:"Güven oluşturan ve nitelikli hasta talebi üreten dijital iletişim.",problem:"Sağlık iletişiminde görünürlük kadar güven, doğru bilgilendirme ve mevzuata uygunluk da önemlidir.",solutions:["Google arama kampanyaları","Yerel görünürlük ve harita profili","Kurumsal sosyal medya dili","Talep ve randevu dönüşüm takibi"]},
 "restoran-ve-kafe":{title:"Restoran & Kafe",headline:"Yakınınızdaki müşterinin sizi bulmasını ve tercih etmesini sağlayın.",problem:"Yerel yeme-içme işletmelerinde harita görünürlüğü, yorumlar, menü sunumu ve sosyal kanıt birlikte karar oluşturur.",solutions:["Google İşletme Profili","Harita ve konum reklamları","Sosyal medya içerik planı","Kampanya ve rezervasyon sayfaları"]},
 "egitim":{title:"Eğitim",headline:"Doğru öğrenci adayına doğru programı doğru anda anlatın.",problem:"Eğitim kararları uzun bir araştırma sürecine dayanır. İçerik, güven ve düzenli takip talebin niteliğini belirler.",solutions:["Program bazlı Google Ads","Tanıtım ve başvuru sayfaları","Sosyal medya içerik serileri","Başvuru dönüşüm ölçümü"]},
 "sanayi-ve-b2b":{title:"Sanayi & B2B",headline:"Uzun satış döngüsünü nitelikli görüşmelere dönüştürün.",problem:"B2B müşteriler teknik yeterlilik, güven ve referans ister. Görünürlük doğru karar vericilere doğru içerikle ulaşmalıdır.",solutions:["Arama ve LinkedIn stratejisi","Kurumsal web ve ürün sayfaları","Teknik SEO ve içerik planı","Nitelikli form ve teklif akışı"]},
 "turizm":{title:"Turizm",headline:"Aracı bağımlılığını azaltın, doğrudan talebi büyütün.",problem:"Turizmde sezon, lokasyon, fiyat ve güven sinyalleri aynı anda yönetilmelidir. Kampanya planı talep dönemlerine göre değişir.",solutions:["Google ve Meta performans reklamları","Çok dilli landing page","Harita ve yorum yönetimi","Rezervasyon dönüşüm takibi"]},
 "moda-ve-giyim":{title:"Moda & Giyim",headline:"Koleksiyonları güçlü kreatif ve doğru ürün verisiyle büyütün.",problem:"Moda müşterisi ürünü kombin, güven, beden, teslimat ve sosyal kanıt üzerinden değerlendirir. Reklam ile mağaza deneyimi aynı dili konuşmalıdır.",solutions:["Meta katalog ve koleksiyon kampanyaları","Google Shopping ve marka aramaları","Kreatif test ve içerik üretim planı","Sepet ve tekrar satın alma optimizasyonu"]},
 "kozmetik-ve-bakim":{title:"Kozmetik & Bakım",headline:"Ürün faydasını güvenilir içerik ve tekrar satın alma sistemiyle anlatın.",problem:"Kozmetikte iddia dili, kullanıcı deneyimi, içerik üreticileri ve ürün eğitimi satın alma kararını doğrudan etkiler.",solutions:["Ürün eğitim içerikleri ve kreatifler","Meta ve Google performans kampanyaları","CRM ve yeniden satın alma akışları","Yorum ve kullanıcı deneyimi yönetimi"]},
 "gida-ve-takviye":{title:"Gıda & Takviye",headline:"Doğru ürünü doğru beklentiyle buluşturan güvenli dijital büyüme.",problem:"Gıda ve takviyede ürün bilgisi, mevzuata uygun iletişim, stok, kargo ve tekrar sipariş deneyimi birlikte yönetilmelidir.",solutions:["Mevzuata duyarlı içerik planı","Arama ve alışveriş kampanyaları","Abonelik ve tekrar sipariş kurgusu","Ürün sayfası ve güven sinyalleri"]},
 "mobilya-ve-dekorasyon":{title:"Mobilya & Dekorasyon",headline:"Uzun karar sürecini ilham, bilgi ve güçlü teklif akışıyla yönetin.",problem:"Mobilyada ölçü, malzeme, teslimat ve yaşam alanı uyumu gibi çok sayıda karar vardır. İçerik, mağaza ziyareti ve teklif süreci birbirine bağlanmalıdır.",solutions:["Koleksiyon ve oda bazlı içerik planı","Google arama ve yerel kampanyalar","Proje, teklif ve mağaza randevusu akışı","Instagram ve yeniden pazarlama"]},
 "elektronik":{title:"Elektronik",headline:"Fiyat rekabetinin yanında güven ve teknik bilgi kazandırsın.",problem:"Elektronikte müşteri yoğun karşılaştırma yapar. Ürün verisi, fiyat, stok, garanti ve güven sinyallerinin tutarlı olması gerekir.",solutions:["Shopping feed ve ürün verisi optimizasyonu","Fiyat ve kategori bazlı kampanyalar","Karşılaştırma ve rehber içerikleri","Sepet terk ve yeniden pazarlama akışları"]}
} as const;export type SectorSlug=keyof typeof sectors;
